import { ProjectMetadata } from "@/types/types";

export const config = {
  author: {
    name: "Nyein Phyo Aung",
    email: "nyeinphyoaung.edu@gmail.com",
    url: "https://nyeinphyoaung.com",
    image: "/avatar.jpg",
    title: "Software Engineer",
    bio: "I'm a software engineer with a passion for building web applications and mobile applications.",
    location: "Yangon, Myanmar",
    social: {
      github: "https://github.com/its-nyein",
      linkedin: "https://www.linkedin.com/in/nyeinphyoaung/",
      twitter: "https://x.com/its_nyein",
      facebook: "https://www.facebook.com/nyeinphyoaung.dev/",
    },
    blogs: {
      postsPerPage: 10,
    },
  },
};

export const allSkills = [
  { name: "HTML", icon: "HTMLIcon", color: "text-orange-600" },
  { name: "CSS", icon: "CSSIcon", color: "text-blue-600" },
  { name: "JavaScript", icon: "JavaScriptIcon", color: "text-yellow-500" },
  { name: "TypeScript", icon: "TypeScriptIcon", color: "text-blue-700" },
  { name: "React.js", icon: "ReactJsIcon", color: "text-cyan-500" },
  { name: "Angular", icon: "AngularIcon", color: "text-red-600" },
  { name: "Vue.js", icon: "VueJsIcon", color: "text-green-600" },
  { name: "Next.js", icon: "NextJsIcon", color: "text-gray-900" },
  { name: "Vite", icon: "ViteIcon", color: "text-purple-600" },
  { name: "Shadcn UI", icon: "ShadcnIcon", color: "text-gray-800" },
  { name: "MUI Material", icon: "MUIIcon", color: "text-blue-500" },
  { name: "Redux Toolkit", icon: "ReduxIcon", color: "text-purple-700" },
  { name: "Zod", icon: "ZodIcon", color: "text-blue-600" },
  { name: "Zustand", icon: "ZustandIcon", color: "text-orange-600" },
  { name: "Tanstack Query", icon: "TanStackQueryIcon", color: "text-red-500" },
  { name: "Tanstack Table", icon: "TanstackTableIcon", color: "text-red-500" },
  { name: "Node.js", icon: "NodeJsIcon", color: "text-green-700" },
  { name: "Express.js", icon: "ExpressJsIcon", color: "text-gray-700" },
  { name: "NestJs", icon: "NestJSIcon", color: "text-red-600" },
  { name: "MySQL", icon: "MySQLIcon", color: "text-blue-600" },
  { name: "MSSQL", icon: "MSSQLIcon", color: "text-red-700" },
  { name: "PrismaORM", icon: "PrismaIcon", color: "text-gray-800" },
  { name: "TailwindCSS", icon: "TailwindCSSIcon", color: "text-blue-500" },
  { name: "SQLite", icon: "SQLiteIcon", color: "text-blue-500" },
  { name: "PostgreSQL", icon: "PostgreSQLIcon", color: "text-blue-700" },
  { name: "Firebase", icon: "FirebaseIcon", color: "text-orange-500" },
  { name: "MongoDB", icon: "MongoDBIcon", color: "text-green-600" },
  { name: "Git", icon: "GitIcon", color: "text-orange-600" },
  { name: "Linux", icon: "LinuxIcon", color: "text-gray-900" },
  { name: "AWS", icon: "AWSIcon", color: "text-yellow-500" },
];

export const PROJECT_METADATA: Record<string, ProjectMetadata> = {
  "shadcn-admin": {
    title: "Shadcn Admin",
    tags: ["Next.js", "TypeScript", "Shadcn/ui", "TailwindCSS"],
    icon: "Grid",
  },
  moviemissile: {
    title: "Moviemissile",
    tags: ["React.js", "TypeScript", "TailwindCSS", "Firebase"],
    icon: "Rocket",
  },
  "bougette-backend": {
    title: "Bougette Backend",
    tags: ["Go", "Echo", "AWS-S3", "Gorm", "MySQL"],
    icon: "Wallet",
  },
  "aerovex-backend": {
    title: "Aerovex Backend",
    tags: ["Nest.js", "TypeScript", "AWS-S3", "PostgreSQL", "Nest-RBAC"],
    icon: "Plane",
  },
  "nyein-terminal": {
    title: "Nyein Terminal",
    tags: ["React.js", "TypeScript", "TailwindCSS"],
    icon: "Terminal",
  },
};

export const FEATURED_PROJECTS = Object.keys(PROJECT_METADATA);

export const EXPERIENCE_DATA = [
  {
    id: 1,
    role: "Web Developer",
    company: "Plus Talent",
    companyUrl: "https://www.plustalent.co/",
    location: "Yangon, Myanmar",
    locationType: "On-site",
    type: "Full Time",
    startDate: "Aug 2025",
    endDate: "Present",
    description:
      "Working as a Full Stack Web Developer building modern web applications with cutting-edge technologies.",
    techStack: [
      "TypeScript",
      "React.js",
      "Next.js",
      "TailwindCSS",
      "Shadcn UI",
      "MUI",
      "Tanstack Query",
      "Tanstack Table",
      "React Hook Form",
      "Node.js",
      "Nest.js",
      "Prisma",
      "MySQL",
      "PostgreSQL",
      "Zod",
      "Zustand",
      "AWS",
    ],
    logo: "/companies/plus-impact.png",
  },
  {
    id: 2,
    role: "Full-stack Developer",
    company: "Blue Ocean Myanmar",
    companyUrl: "https://blueoceanmm.com/",
    location: "Yangon, Myanmar",
    locationType: "On-site",
    type: "Full Time",
    startDate: "Jan 2025",
    endDate: "Jun 2025",
    description:
      "Developed full-stack web applications using modern JavaScript frameworks and cloud technologies.",
    techStack: [
      "TypeScript",
      "React.js",
      "Next.js",
      "Vue.js",
      "TailwindCSS",
      "Bootstrap",
      "Shadcn UI",
      "MUI",
      "Tanstack Query",
      "Tanstack Table",
      "React Hook Form",
      "Node.js",
      "Nest.js",
      "Prisma",
      "MySQL",
      "PostgreSQL",
      "Zod",
      "Zustand",
      "AWS",
    ],
    logo: "/companies/blueocean.png",
  },
  {
    id: 3,
    role: "Associate Developer",
    company: "Partner Associates",
    companyUrl: "https://partnerassociates.com/",
    location: "Yangon, Myanmar",
    locationType: "On-site",
    type: "Full Time",
    startDate: "Apr 2024",
    endDate: "Nov 2024",
    description:
      "Worked on enterprise applications using Angular and .NET stack with Azure cloud services.",
    techStack: [
      "TypeScript",
      "JavaScript",
      "Angular",
      "Node.js",
      ".Net",
      "DevExtereme",
      "DevExpress",
      "MSSQL",
      "SQLite",
      "MySQL",
      "Azure",
    ],
    logo: "/companies/partner-associates.png",
  },
];
